version: 2

sphinx:
  configuration: docs/conf.py

# don't build PDF and ePub
formats: []

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  jobs:
    post_checkout:
      - cp -r Recipes/ docs/
      - cp -r Tutorials/ docs/

python:
  install:
    - requirements: docs/requirements.txt
