version: 2

sphinx:
  configuration: docs/conf.py

# don't build PDF and ePub
formats: []

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  jobs:
    post_checkout:
      - cp -r 01-Cooking-Lessons-101/ docs/
      - cp -r 02-Appetisers/ docs/
      - cp -r 03-Mains/ docs/
      - cp -r 04-Local-Dishes/ docs/

python:
  install:
    - requirements: docs/requirements.txt
