version: 2

sphinx:
  configuration: docs/conf.py

# don't build PDF and ePub
formats: []

build:
  os: ubuntu-24.04
  tools:
    python: "3"
  jobs:
    post_checkout:
      - cp -r 01-Cooking-Tutorials/ docs/
      - cp -r 02-Easy-Recipes/ docs/
      - cp -r 03-Advanced-Recipes/ docs/
      - cp -r 04-Regional-Specialties/ docs/

python:
  install:
    - requirements: docs/requirements.txt
