project: x77
queue: normal
walltime: 02:00:00
jobname: mom6_GIPPSLAND
ncpus: 82
jobfs: 10GB

shortpath: /scratch/x77

model: mom6
input:
    - /scratch/v45/ab8992/mom6/regional_configs/gippsland
#    - /g/data/ua8/JRA55-do/RYF/v1-3/
    - /g/data/ik11/inputs/JRA-55/RYF/v1-3/
# release exe
exe: /g/data/x77/ahg157/exes/MOM6_SIS2/symmetric_FMS2-e7d09b7
# debug exe
#exe: /g/data/x77/ahg157/exes/MOM6_SIS2/symmetric_FMS2-9bc3419a

collate: false
#runlog: true
storage:
  gdata:
    - ua8
    - x77
    - ik11

mpi:
  module: openmpi/4.1.2
